FROM python:3.9

COPY requirements.txt /requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /requirements.txt

COPY ./celery /celery_tasks
COPY ./common/metric_name.py celery_tasks
WORKDIR /celery_tasks
