version: "3"

services:
  fastapi:
    build:
      context: .
      dockerfile: DockerfileApp
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: sh web_starter.sh

  worker:
    build:
      context: .
      dockerfile: DockerfileCelery
    env_file:
      - .env
    depends_on:
      - redis
    command: sh worker_starter.sh

  redis:
    image: redis
