version: "3"

services:
  web:
    build:
      context: .
      dockerfile: DockerfileA.web
    image: web:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: sh web_starter.sh

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: worker:latest
    env_file:
      - .env
    depends_on:
      - redis
    command: sh worker_starter.sh

  redis:
    image: redis
