FROM python:3.9

COPY requirements.txt /requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /requirements.txt

COPY ./app /app
COPY ./common/metric_name.py app
WORKDIR /app

EXPOSE 8000

