version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: sh web_starter.sh

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    command: sh worker_starter.sh

